Added slicing functions in BWR files
Helveg/bwpy pull request #12
Opened 2022-10-11 11:39 UTC by Igor10798

Added `_Slice` and `_ChannelSlicer _TimeSlicer _Slicer` classes.  

**tests**  
Added `tests.test_slicing` testing file.

**docs**
Updated docs.

2022-10-11 16:17 UTC, Helveg commented on bwpy/__init__.py
> +            self.__post_init__()
Is `__post_init__` defined anywhere?

2022-10-11 16:35 UTC, Helveg requested changes
Looks great!

2022-10-11 16:35 UTC, Helveg commented on bwpy/__init__.py
> +        #self._file.n_channel =
```suggestion
```

2022-10-12 15:17 UTC, Igor10798 commented on setup.py
> +    install_requires=["h5py", "numpy"],
I wanted to check it out but when I try to run `python -m unittest tests.test_file.TestUserInfo.test_raw_user_info` to check if the test is okay from the `bwpy` folder I receive the following error:  
```
File "path_to_module\bwpy\tests\test_file.py", line 4, in <module>
    from helpers import get_sample_path, open_sample, open_sample_copy, samples
ModuleNotFoundError: No module named 'helpers'
```

2022-10-12 15:18 UTC, Igor10798 commented on bwpy/__init__.py
> +            self.__post_init__()
Line 210  
```
def __post_init__(self):
        _Slice.__init__(self, self)
```

2023-07-14 15:11 UTC, igorcantele commented
Let my contribution become live :(

2023-08-22 15:34 UTC, Helveg requested changes

2023-08-22 15:34 UTC, Helveg commented on docs/source/index.rst
> +      #will return the slice of the first 10 temporal recordings with a step of 2
```suggestion
      # Return the slice of the first 10 temporal recordings with a step of 2
      datafile.t[0:10:2]
```

2023-08-22 15:34 UTC, Helveg commented on docs/source/index.rst
> +      #will return the slice of the block of the first 10x10 channels
```suggestion
      # Return the slice of the block of the first 10x10 channels
      datafile.ch[0:10, 0: 10]
```

2023-08-22 15:34 UTC, Helveg commented on docs/source/index.rst
> +      #will return the slice of the first 10 temporal recordings of the first channel
```suggestion
      # Return the slice of the first 10 temporal recordings of the first channel
      datafile.t[0:10].ch[0, 0]
```

2023-08-22 15:35 UTC, Helveg approved these changes

2023-08-22 16:36 UTC, merged